/**
 * Tradeflow Global - Core Type Definitions
 * 
 * SOLID Principle: Single Responsibility Principle (SRP)
 * This file strictly houses domain interface definitions and data models for
 * prices, quotes, order tickets, open positions, and account summary state.
 */

export type CurrencyPairSymbol = 'EUR/USD' | 'GBP/USD' | 'USD/JPY' | 'AUD/USD' | 'USD/CAD' | 'XAU/USD' | 'BTC/USD';

export type OrderType = 'MARKET' | 'LIMIT' | 'STOP';
export type TradeSide = 'BUY' | 'SELL';
export type PositionStatus = 'OPEN' | 'CLOSED' | 'CANCELLED';

/**
 * Real-Time Forex Quote Object
 * Emitted by forexPriceService on price tick updates
 */
export interface ForexQuote {
  symbol: CurrencyPairSymbol;
  bid: number;
  ask: number;
  spreadPips: number;
  high24h: number;
  low24h: number;
  changePercent24h: number;
  lastUpdated: number;
  priceDirection: 'UP' | 'DOWN' | 'SAME';
}

/**
 * OHLC Candlestick Data Bar for Technical Charts
 */
export interface CandlestickBar {
  timestamp: number;
  timeLabel: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  ema20?: number;
  ema50?: number;
  rsi14?: number;
}

/**
 * Trade Order Request Model
 * Generated by OrderEntryTicket component
 */
export interface TradeOrderRequest {
  symbol: CurrencyPairSymbol;
  side: TradeSide;
  type: OrderType;
  volumeLots: number;
  stopLossPips?: number;
  takeProfitPips?: number;
  targetPrice?: number;
  leverage: number;
}

/**
 * Active Trade Position Model
 * Managed by orderExecutionService
 */
export interface Position {
  id: string;
  symbol: CurrencyPairSymbol;
  side: TradeSide;
  volumeLots: number;
  entryPrice: number;
  currentPrice: number;
  stopLossPrice?: number;
  takeProfitPrice?: number;
  unrealizedPnL: number;
  realizedPnL: number;
  marginUsed: number;
  swapFee: number;
  commission: number;
  openTime: number;
  closeTime?: number;
  status: PositionStatus;
}

/**
 * Account Financial State Summary
 */
export interface AccountSummary {
  balance: number;
  equity: number;
  marginUsed: number;
  freeMargin: number;
  marginLevelPercent: number;
  totalUnrealizedPnL: number;
  totalRealizedPnL: number;
  winRatePercent: number;
  totalTradesExecuted: number;
}

/**
 * Economic Calendar News Event Item
 */
export interface EconomicEvent {
  id: string;
  time: string;
  currency: 'USD' | 'EUR' | 'GBP' | 'JPY' | 'AUD';
  eventName: string;
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  actual?: string;
  forecast: string;
  previous: string;
}
